// Textos do site, um objeto por idioma. JSON puro depois do `=` (lido por tools/check_i18n.py).
window.STRINGS = {
  "pt-BR": {
    "pageTitle": "Floresta dos Bichinhos — jogo educativo e gratuito para crianças",
    "skip": "Pular para o conteúdo",
    "navGame": "O jogo",
    "navPhases": "Fases",
    "navFamilies": "Para pais e escolas",
    "navContribute": "Contribuir",
    "navDownload": "Baixar",
    "menuOpen": "Abrir menu",
    "langLabel": "Idioma",
    "heroEyebrow": "Doma Studios apresenta",
    "heroTitle": "Brincar e aprender na floresta",
    "heroLede": "Grátis, sem anúncios, para crianças de 3 a 7 anos.",
    "heroText": "Quatro bichinhos, um monte de brincadeira e nenhuma pressa. Feito para as mãozinhas que estão começando agora.",
    "ctaDownload": "Baixar o jogo",
    "soon": "Em breve",
    "platformsLabel": "Disponível para",
    "heroShotAlt": "Tela do Modo Livre do jogo, com os cartões das fases",
    "g1Title": "Sem anúncios",
    "g1Text": "Nenhuma propaganda, em momento nenhum.",
    "g2Title": "Sem compras",
    "g2Text": "Nada é vendido dentro do jogo.",
    "g3Title": "Funciona offline",
    "g3Text": "Brinca no avião, no carro, onde não pega nada.",
    "g4Title": "Sem coleta de dados",
    "g4Text": "Sem cadastro, sem rastreio, sem conversa com estranhos.",
    "g5Title": "Código aberto",
    "g5Text": "Transparente, seguro e feito com a comunidade.",
    "trailerTitle": "Uma floresta de brincadeiras",
    "trailerLede": "Assista e veja como é brincar com os bichinhos.",
    "trailerLabel": "Vídeo do jogo Floresta dos Bichinhos",
    "peekTitle": "Espie a floresta",
    "peekLede": "Conheça algumas fases e veja como é divertido aprender brincando.",
    "prevSlide": "Tela anterior",
    "nextSlide": "Próxima tela",
    "slideGo": "Ir para a tela",
    "slide1": "Menu principal",
    "slide1Tag": "Tudo começa aqui",
    "slide2": "Mapa do mundo",
    "slide2Tag": "Uma fase abre a outra",
    "slide3": "O Café da Manhã da Didi",
    "slide3Tag": "Coordenação",
    "slide4": "Recife das Cores",
    "slide4Tag": "Cores",
    "slide5": "Trilha dos Números",
    "slide5Tag": "Números",
    "slide6": "Quebra-cabeça da Sophy",
    "slide6Tag": "Coordenação",
    "slide7": "Jogo da Memória da Didia",
    "slide7Tag": "Memória",
    "slide8": "Jardim Colorido",
    "slide8Tag": "Cores",
    "slide9": "Modo Livre",
    "slide9Tag": "Qualquer fase, a qualquer hora",
    "benefitsTitle1": "Tudo o que a criança ama.",
    "benefitsTitle2": "Tudo o que os pais querem.",
    "b1Title": "Cores, números e letras",
    "b1Text": "Brincadeiras que desenvolvem habilidades de verdade.",
    "b2Title": "Calmo e sem pressa",
    "b2Text": "Sem tempo correndo, sem competição, sem game over.",
    "b3Title": "Vozes dos personagens",
    "b3Text": "Os bichinhos falam e explicam cada brincadeira.",
    "b4Title": "Modo Livre",
    "b4Text": "A criança escolhe a fase que quiser, no seu ritmo.",
    "b5Title": "Português e italiano",
    "b5Text": "Textos e vozes nos dois idiomas — e mais a caminho.",
    "b6Title": "Grátis e aberto",
    "b6Text": "Sempre gratuito, com código aberto para todos.",
    "friendsTitle": "Os quatro bichinhos",
    "friendsLede": "Eles falam com a criança em português e em italiano, e voltam sempre — do primeiro toque na tela até o fim.",
    "friend1": "A coelhinha que recebe todo mundo na porta da floresta.",
    "friend2": "A peixinha do fundo do mar, que adora cor forte.",
    "friend3": "O passarinho apressadinho que enxerga tudo lá de cima.",
    "friend4": "A esquilinha curiosa que nunca sai sem a mochila.",
    "familiesTitle": "Para pais e escolas",
    "familiesText": "Um jogo pensado para o desenvolvimento infantil, em casa e na sala de aula. Uso livre em escolas e projetos educativos, sem cadastro e sem internet.",
    "familiesCta": "Ver as garantias",
    "communityTitle": "Feito por uma comunidade",
    "communityText": "O código é aberto e qualquer pessoa pode ajudar — programando, desenhando, traduzindo ou testando com as crianças. Tudo passa por curadoria para ser bom para os pequenos.",
    "communityCta": "Como contribuir",
    "ctaTitle": "Vamos explorar a floresta juntos?",
    "ctaText": "Grátis para Android, macOS, Linux e Windows. Sem cadastro, sem cartão.",
    "footLine": "Feito com carinho para quem está começando a brincar.",
    "footPrivacy": "Política de privacidade",
    "footLicenses": "Licenças",
    "footSiteCode": "Código deste site",
    "footGameCode": "Código do jogo",
    "pvPageTitle": "Política de privacidade — Floresta dos Bichinhos",
    "pvBack": "Voltar ao site",
    "pvTitle": "Política de privacidade",
    "pvUpdated": "Última atualização: 27 de setembro de 2026",
    "pvIntro": "Floresta dos Bichinhos é um jogo educativo e gratuito para crianças, publicado por Doma Studios. Esta política explica como o jogo e este site lidam com informações.",
    "pvSummaryTitle": "Resumo",
    "pvSummary": "O jogo não coleta, não envia e não compartilha nenhum dado pessoal. Ele funciona inteiramente no aparelho, sem cadastro, sem login e sem internet.",
    "pvNotTitle": "Dados que o jogo não coleta",
    "pvNot1": "Nome, e-mail, telefone ou qualquer dado de identificação",
    "pvNot2": "Localização",
    "pvNot3": "Contatos, fotos, arquivos, microfone ou câmera",
    "pvNot4": "Identificadores de publicidade ou do aparelho",
    "pvNot5": "Dados de uso, análise de comportamento ou telemetria",
    "pvLocalTitle": "O que fica guardado no aparelho",
    "pvLocal": "Para a criança não perder o que já jogou, o jogo guarda no próprio aparelho: o progresso e as estrelas das fases, os recordes do Modo Livre, o volume da música e dos efeitos, o idioma e a qualidade gráfica. Nada disso sai do aparelho, e tudo é apagado quando o jogo é desinstalado.",
    "pvNetTitle": "Internet, anúncios e compras",
    "pvNet": "O jogo não usa a internet, não exibe anúncios, não tem compras e não integra serviços de análise, redes sociais ou publicidade.",
    "pvKidsTitle": "Crianças",
    "pvKids": "O jogo é feito para crianças. Como nada é coletado, não há tratamento de dados de menores de idade. Não há links externos, chat nem qualquer forma de conversa com outras pessoas dentro do jogo.",
    "pvSiteTitle": "Este site",
    "pvSite": "Este site não usa cookies, analytics nem serviços de terceiros. A única informação guardada é o idioma escolhido, no próprio navegador.",
    "pvChangesTitle": "Alterações",
    "pvChanges": "Se o jogo ou o site passarem a tratar dados de alguma forma, esta página será atualizada antes da mudança, com nova data.",
    "pvContactTitle": "Contato",
    "pvContact": "Dúvidas sobre privacidade: lucassdoro@hotmail.com"
  },
  "it": {
    "pageTitle": "Floresta dos Bichinhos — gioco educativo e gratuito per bambini",
    "skip": "Vai al contenuto",
    "navGame": "Il gioco",
    "navPhases": "Livelli",
    "navFamilies": "Per genitori e scuole",
    "navContribute": "Contribuisci",
    "navDownload": "Scarica",
    "menuOpen": "Apri il menu",
    "langLabel": "Lingua",
    "heroEyebrow": "Doma Studios presenta",
    "heroTitle": "Giocare e imparare nella foresta",
    "heroLede": "Gratis, senza pubblicità, per bambini dai 3 ai 7 anni.",
    "heroText": "Quattro animaletti, tanti giochi e nessuna fretta. Pensato per le manine che stanno appena cominciando.",
    "ctaDownload": "Scarica il gioco",
    "soon": "Presto",
    "platformsLabel": "Disponibile per",
    "heroShotAlt": "Schermata della Modalità Libera del gioco, con le schede dei livelli",
    "g1Title": "Senza pubblicità",
    "g1Text": "Nessuna pubblicità, in nessun momento.",
    "g2Title": "Nessun acquisto",
    "g2Text": "Non si vende niente dentro il gioco.",
    "g3Title": "Funziona offline",
    "g3Text": "Si gioca in aereo, in macchina, dove non prende niente.",
    "g4Title": "Nessun dato raccolto",
    "g4Text": "Senza registrazione, senza tracciamento, senza estranei.",
    "g5Title": "Codice aperto",
    "g5Text": "Trasparente, sicuro e fatto insieme alla comunità.",
    "trailerTitle": "Una foresta di giochi",
    "trailerLede": "Guarda com'è giocare con gli animaletti.",
    "trailerLabel": "Video del gioco Floresta dos Bichinhos",
    "peekTitle": "Sbircia nella foresta",
    "peekLede": "Scopri alcuni livelli e guarda quanto è divertente imparare giocando.",
    "prevSlide": "Schermata precedente",
    "nextSlide": "Schermata successiva",
    "slideGo": "Vai alla schermata",
    "slide1": "Menu principale",
    "slide1Tag": "Tutto comincia qui",
    "slide2": "Mappa del mondo",
    "slide2Tag": "Un livello apre l'altro",
    "slide3": "La Colazione di Didi",
    "slide3Tag": "Coordinazione",
    "slide4": "Barriera dei Colori",
    "slide4Tag": "Colori",
    "slide5": "Il Sentiero dei Numeri",
    "slide5Tag": "Numeri",
    "slide6": "Il Puzzle di Sophy",
    "slide6Tag": "Coordinazione",
    "slide7": "Il Memory di Didia",
    "slide7Tag": "Memoria",
    "slide8": "Giardino Colorato",
    "slide8Tag": "Colori",
    "slide9": "Modalità Libera",
    "slide9Tag": "Qualsiasi livello, in qualsiasi momento",
    "benefitsTitle1": "Tutto ciò che i bambini amano.",
    "benefitsTitle2": "Tutto ciò che i genitori vogliono.",
    "b1Title": "Colori, numeri e lettere",
    "b1Text": "Giochi che sviluppano abilità vere.",
    "b2Title": "Calmo e senza fretta",
    "b2Text": "Niente tempo che scorre, niente gare, niente game over.",
    "b3Title": "Voci dei personaggi",
    "b3Text": "Gli animaletti parlano e spiegano ogni gioco.",
    "b4Title": "Modalità Libera",
    "b4Text": "Il bambino sceglie il livello che vuole, con i suoi tempi.",
    "b5Title": "Portoghese e italiano",
    "b5Text": "Testi e voci nelle due lingue — e altre in arrivo.",
    "b6Title": "Gratis e aperto",
    "b6Text": "Sempre gratuito, con codice aperto per tutti.",
    "friendsTitle": "I quattro animaletti",
    "friendsLede": "Parlano al bambino in portoghese e in italiano, e tornano sempre — dal primo tocco sullo schermo fino alla fine.",
    "friend1": "La coniglietta che accoglie tutti all'ingresso della foresta.",
    "friend2": "Il pesciolino del fondale, che adora i colori accesi.",
    "friend3": "L'uccellino frettoloso che vede tutto dall'alto.",
    "friend4": "La scoiattolina curiosa che non esce mai senza zaino.",
    "familiesTitle": "Per genitori e scuole",
    "familiesText": "Un gioco pensato per lo sviluppo dei bambini, a casa e in classe. Uso libero nelle scuole e nei progetti educativi, senza registrazione e senza internet.",
    "familiesCta": "Vedi le garanzie",
    "communityTitle": "Fatto da una comunità",
    "communityText": "Il codice è aperto e chiunque può aiutare — programmando, disegnando, traducendo o provando il gioco con i bambini. Tutto passa da una revisione per essere adatto ai più piccoli.",
    "communityCta": "Come contribuire",
    "ctaTitle": "Esploriamo insieme la foresta?",
    "ctaText": "Gratis per Android, macOS, Linux e Windows. Senza registrazione, senza carta.",
    "footLine": "Fatto con affetto per chi sta appena imparando a giocare.",
    "footPrivacy": "Informativa sulla privacy",
    "footLicenses": "Licenze",
    "footSiteCode": "Codice di questo sito",
    "footGameCode": "Codice del gioco",
    "pvPageTitle": "Informativa sulla privacy — Floresta dos Bichinhos",
    "pvBack": "Torna al sito",
    "pvTitle": "Informativa sulla privacy",
    "pvUpdated": "Ultimo aggiornamento: 27 settembre 2026",
    "pvIntro": "Floresta dos Bichinhos è un gioco educativo e gratuito per bambini, pubblicato da Doma Studios. Questa informativa spiega come il gioco e questo sito trattano le informazioni.",
    "pvSummaryTitle": "In breve",
    "pvSummary": "Il gioco non raccoglie, non invia e non condivide alcun dato personale. Funziona interamente sul dispositivo, senza registrazione, senza login e senza internet.",
    "pvNotTitle": "Dati che il gioco non raccoglie",
    "pvNot1": "Nome, e-mail, telefono o qualsiasi dato identificativo",
    "pvNot2": "Posizione",
    "pvNot3": "Contatti, foto, file, microfono o fotocamera",
    "pvNot4": "Identificatori pubblicitari o del dispositivo",
    "pvNot5": "Dati di utilizzo, analisi del comportamento o telemetria",
    "pvLocalTitle": "Cosa resta salvato sul dispositivo",
    "pvLocal": "Perché il bambino non perda ciò che ha già giocato, il gioco salva sul dispositivo: i progressi e le stelle dei livelli, i record della Modalità Libera, il volume della musica e degli effetti, la lingua e la qualità grafica. Nulla esce dal dispositivo e tutto viene cancellato quando il gioco viene disinstallato.",
    "pvNetTitle": "Internet, pubblicità e acquisti",
    "pvNet": "Il gioco non usa internet, non mostra pubblicità, non ha acquisti e non integra servizi di analisi, social network o pubblicità.",
    "pvKidsTitle": "Bambini",
    "pvKids": "Il gioco è fatto per i bambini. Poiché non viene raccolto nulla, non c'è trattamento di dati di minori. Non ci sono link esterni, chat né alcuna forma di conversazione con altre persone all'interno del gioco.",
    "pvSiteTitle": "Questo sito",
    "pvSite": "Questo sito non usa cookie, analytics né servizi di terzi. L'unica informazione salvata è la lingua scelta, nel browser stesso.",
    "pvChangesTitle": "Modifiche",
    "pvChanges": "Se il gioco o il sito dovessero trattare dati in qualche modo, questa pagina verrà aggiornata prima della modifica, con una nuova data.",
    "pvContactTitle": "Contatti",
    "pvContact": "Domande sulla privacy: lucassdoro@hotmail.com"
  }
};
